// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/pgx-driver/transaction/manager.go
//
// Generated by this command:
//
//	mockgen -source=pkg/pgx-driver/transaction/manager.go -destination=internal/services/wallet/mocks/manager.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	pgx_driver "wallet-service/pkg/pgx-driver"

	gomock "go.uber.org/mock/gomock"
)

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// ExecuteInTransaction mocks base method.
func (m *MockManager) ExecuteInTransaction(ctx context.Context, tsName string, fn func(pgx_driver.QueryExecuter) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteInTransaction", ctx, tsName, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// ExecuteInTransaction indicates an expected call of ExecuteInTransaction.
func (mr *MockManagerMockRecorder) ExecuteInTransaction(ctx, tsName, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteInTransaction", reflect.TypeOf((*MockManager)(nil).ExecuteInTransaction), ctx, tsName, fn)
}
