// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/wallet/wallet.go
//
// Generated by this command:
//
//	mockgen -source=internal/services/wallet/wallet.go -destination=internal/services/wallet/mocks/mock_wallet.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"
	models "wallet-service/internal/domain/models"
	pgx_driver "wallet-service/pkg/pgx-driver"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSaverWallet is a mock of SaverWallet interface.
type MockSaverWallet struct {
	ctrl     *gomock.Controller
	recorder *MockSaverWalletMockRecorder
	isgomock struct{}
}

// MockSaverWalletMockRecorder is the mock recorder for MockSaverWallet.
type MockSaverWalletMockRecorder struct {
	mock *MockSaverWallet
}

// NewMockSaverWallet creates a new mock instance.
func NewMockSaverWallet(ctrl *gomock.Controller) *MockSaverWallet {
	mock := &MockSaverWallet{ctrl: ctrl}
	mock.recorder = &MockSaverWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSaverWallet) EXPECT() *MockSaverWalletMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockSaverWallet) CreateWallet(ctx context.Context, id uuid.UUID, balance int64) (*models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, id, balance)
	ret0, _ := ret[0].(*models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockSaverWalletMockRecorder) CreateWallet(ctx, id, balance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockSaverWallet)(nil).CreateWallet), ctx, id, balance)
}

// MockGetterWallet is a mock of GetterWallet interface.
type MockGetterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockGetterWalletMockRecorder
	isgomock struct{}
}

// MockGetterWalletMockRecorder is the mock recorder for MockGetterWallet.
type MockGetterWalletMockRecorder struct {
	mock *MockGetterWallet
}

// NewMockGetterWallet creates a new mock instance.
func NewMockGetterWallet(ctrl *gomock.Controller) *MockGetterWallet {
	mock := &MockGetterWallet{ctrl: ctrl}
	mock.recorder = &MockGetterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetterWallet) EXPECT() *MockGetterWalletMockRecorder {
	return m.recorder
}

// GetWallet mocks base method.
func (m *MockGetterWallet) GetWallet(ctx context.Context, id uuid.UUID) (*models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, id)
	ret0, _ := ret[0].(*models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockGetterWalletMockRecorder) GetWallet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockGetterWallet)(nil).GetWallet), ctx, id)
}

// MockOperationSaver is a mock of OperationSaver interface.
type MockOperationSaver struct {
	ctrl     *gomock.Controller
	recorder *MockOperationSaverMockRecorder
	isgomock struct{}
}

// MockOperationSaverMockRecorder is the mock recorder for MockOperationSaver.
type MockOperationSaverMockRecorder struct {
	mock *MockOperationSaver
}

// NewMockOperationSaver creates a new mock instance.
func NewMockOperationSaver(ctrl *gomock.Controller) *MockOperationSaver {
	mock := &MockOperationSaver{ctrl: ctrl}
	mock.recorder = &MockOperationSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOperationSaver) EXPECT() *MockOperationSaverMockRecorder {
	return m.recorder
}

// CreateOperation mocks base method.
func (m *MockOperationSaver) CreateOperation(ctx context.Context, tx pgx_driver.QueryExecuter, operation *models.Operation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOperation", ctx, tx, operation)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOperation indicates an expected call of CreateOperation.
func (mr *MockOperationSaverMockRecorder) CreateOperation(ctx, tx, operation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOperation", reflect.TypeOf((*MockOperationSaver)(nil).CreateOperation), ctx, tx, operation)
}

// MockBalanceUpdaterWallet is a mock of BalanceUpdaterWallet interface.
type MockBalanceUpdaterWallet struct {
	ctrl     *gomock.Controller
	recorder *MockBalanceUpdaterWalletMockRecorder
	isgomock struct{}
}

// MockBalanceUpdaterWalletMockRecorder is the mock recorder for MockBalanceUpdaterWallet.
type MockBalanceUpdaterWalletMockRecorder struct {
	mock *MockBalanceUpdaterWallet
}

// NewMockBalanceUpdaterWallet creates a new mock instance.
func NewMockBalanceUpdaterWallet(ctrl *gomock.Controller) *MockBalanceUpdaterWallet {
	mock := &MockBalanceUpdaterWallet{ctrl: ctrl}
	mock.recorder = &MockBalanceUpdaterWalletMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBalanceUpdaterWallet) EXPECT() *MockBalanceUpdaterWalletMockRecorder {
	return m.recorder
}

// DecreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) DecreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, walletID uuid.UUID, amount int64) (int64, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseBalance", ctx, tx, walletID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DecreaseBalance indicates an expected call of DecreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) DecreaseBalance(ctx, tx, walletID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).DecreaseBalance), ctx, tx, walletID, amount)
}

// IncreaseBalance mocks base method.
func (m *MockBalanceUpdaterWallet) IncreaseBalance(ctx context.Context, tx pgx_driver.QueryExecuter, walletID uuid.UUID, amount int64) (int64, time.Time, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncreaseBalance", ctx, tx, walletID, amount)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(time.Time)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// IncreaseBalance indicates an expected call of IncreaseBalance.
func (mr *MockBalanceUpdaterWalletMockRecorder) IncreaseBalance(ctx, tx, walletID, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncreaseBalance", reflect.TypeOf((*MockBalanceUpdaterWallet)(nil).IncreaseBalance), ctx, tx, walletID, amount)
}
