// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http-server/handlers/wallet/get/get.go
//
// Generated by this command:
//
//	mockgen -source=internal/http-server/handlers/wallet/get/get.go -destination=internal/http-server/handlers/wallet/get/mocks/mock_get.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "wallet-service/internal/domain/models"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockWalletGetter is a mock of WalletGetter interface.
type MockWalletGetter struct {
	ctrl     *gomock.Controller
	recorder *MockWalletGetterMockRecorder
	isgomock struct{}
}

// MockWalletGetterMockRecorder is the mock recorder for MockWalletGetter.
type MockWalletGetterMockRecorder struct {
	mock *MockWalletGetter
}

// NewMockWalletGetter creates a new mock instance.
func NewMockWalletGetter(ctrl *gomock.Controller) *MockWalletGetter {
	mock := &MockWalletGetter{ctrl: ctrl}
	mock.recorder = &MockWalletGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletGetter) EXPECT() *MockWalletGetterMockRecorder {
	return m.recorder
}

// GetWallet mocks base method.
func (m *MockWalletGetter) GetWallet(ctx context.Context, id uuid.UUID) (*models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWallet", ctx, id)
	ret0, _ := ret[0].(*models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWallet indicates an expected call of GetWallet.
func (mr *MockWalletGetterMockRecorder) GetWallet(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWallet", reflect.TypeOf((*MockWalletGetter)(nil).GetWallet), ctx, id)
}
