// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http-server/handlers/wallet/save/save.go
//
// Generated by this command:
//
//	mockgen -source=internal/http-server/handlers/wallet/save/save.go -destination=internal/http-server/handlers/wallet/save/mocks/mock_save.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	models "wallet-service/internal/domain/models"

	gomock "go.uber.org/mock/gomock"
)

// MockWalletSaver is a mock of WalletSaver interface.
type MockWalletSaver struct {
	ctrl     *gomock.Controller
	recorder *MockWalletSaverMockRecorder
	isgomock struct{}
}

// MockWalletSaverMockRecorder is the mock recorder for MockWalletSaver.
type MockWalletSaverMockRecorder struct {
	mock *MockWalletSaver
}

// NewMockWalletSaver creates a new mock instance.
func NewMockWalletSaver(ctrl *gomock.Controller) *MockWalletSaver {
	mock := &MockWalletSaver{ctrl: ctrl}
	mock.recorder = &MockWalletSaverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWalletSaver) EXPECT() *MockWalletSaverMockRecorder {
	return m.recorder
}

// CreateWallet mocks base method.
func (m *MockWalletSaver) CreateWallet(ctx context.Context, amount int64) (*models.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", ctx, amount)
	ret0, _ := ret[0].(*models.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockWalletSaverMockRecorder) CreateWallet(ctx, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockWalletSaver)(nil).CreateWallet), ctx, amount)
}
